### ISSUE TITLE
Initial meeting with NCI

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#13]

**Comment by carpediemkz** [comment]
I prefer Tuesday or Wednesday, Friday is impossible for me

**Comment by aaryani** [comment]
Add the meeting nodes to the github. Please remove the action items and private info.

**Comment by carpediemkz** [comment]
Client requirement:
Export related attributes from the NCI database (GeoNetork, which is XML)
Import the data  into Neo4j, which needs to use XSLY and RD-Switchboard;
Convert the data in Neo4j into .graphml files, which needs to use Bash Script and Neo4j Shell Tools;
Apply visualisations to this graph in Gephi
Further issues:
How to apply different visualisations to this graph
Find visualisation parameters that can be linked to Gestures on LeapMotion

**Comment by aaryani** [comment]
This task is complete. We will have a follow-up meeting with NCI in May.
