### ISSUE TITLE
Demo the Cambridge data - version 1

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#16]

**Comment by zhaolianzhou** [comment]
Requirement:

   

1. The current CLI filter outs all the nodes with no relationship. Any further filtering needs to be done using Gephi
2. Use Gephi command line to apply filters and create a more manageable visualisable file.
3. The visualisation is computationally expensive, not the filtering. When you open the out.graphml, you should be able to apply filter applying any visualisation.
4. Investigate how to set Gephi to do not visualise the graph right after opening the file.
