### ISSUE TITLE
X- Properties are missing from Gephi after importing GraphML

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#18]

**Comment by Meovel** [comment]
The reason properties are missing is due to missing of <key> entry in graphml, and the reason entry is missing is because of not including -t in export command of shell-tool

**Comment by Meovel** [comment]
BTW the doc of neo4j shell-tool has a bit of problem, 
export-graphml [-o out.graphml] [-t] [-r] [match (n:Foo)-[r]->() return n,r]
should be
export-graphml [-t] [-r] [-o out.graphml] [match (n:Foo)-[r]->() return n,r]

**Comment by aaryani** [comment]
-t command solves the issue in CLI files
