### ISSUE TITLE
Requirement Discussion of Four Graphs

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#6]
Requirement Discussion of Four Graphs.

Candidates:
NCI  (limited in size, disconnected clusters, missing identifiers)
ORCID (large scale)
Cambridge  DSPACE(medium size, missing connection to control vocabulary)
Sydney (medium size, need clustering)

**Comment by aaryani** [comment]
NCI: Kun
Sydney: Zhaolian
ORCID: Hao
Cambridge: Andy

**Comment by aaryani** [comment]
NCI: Kun
Sydney: Andy
ORCID: Hao
Cambridge: Zhaolian

**Comment by zhaolianzhou** [comment]
Cambridge:
1. The current CLI filter outs all the nodes with no relationship. Any further filtering needs to be done using Gephi
2. Use Gephi command line to apply filters and create a more manageable visualisable file.
3. The visualisation is computationally expensive, not the filtering. When you open the out.graphml, you should be able to apply filter applying any visualisation.

**Comment by zhaolianzhou** [comment]
4. Investigate how to set Gephi to do not visualise the graph right after opening the file.

**Comment by zhaolianzhou** [comment]
NCI:
1. How to apply different visualisations to this graph
2. Find visualisation parameters that can be linked to Gestures on LeapMotion
