### ISSUE TITLE
Review and test the current LeapMotion integration 

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#7]

**Comment by aaryani** [comment]
Questions to answer:
- How does the current code work? -> Code review 
- How can we separate the code to new components?

**Comment by Meovel** [comment]
Works fine for Mac/Windows, meeting for sorting out Ubuntu issue is scheduled at Wednesday 4:00 p.m.

**Comment by aaryani** [comment]
The LeapMotion plugin now works on all machines
