### ISSUE TITLE
Create wiki structure

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#8]
- Meeting Notes

**Comment by aaryani** [comment]
Wiki structure:
-  Meeting notes
-  Installation (Ubuntu, Mac, Andy subsection)
-  Sample data (TBA)

**Comment by Meovel** [comment]
Purposed New Wiki structure:

- Introduction
- Requirement
- Installation
- Sample Data
- Demo Video
- Useful Resources

- Meeting Agendas

**Comment by aaryani** [comment]
It is completed 👍
